export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          title: string;
          description: string;
          short_desc: string;
          brand: string;
          model: string;
          category: string;
          price: string;
          capacity?: string;
          efficiency?: string;
          warranty: string;
          moq: string;
          rating: number;
          reviews: number;
          in_stock: boolean;
          lead_time: string;
          features: string[];
          applications: string[];
          certifications: string[];
          specifications: Record<string, string>;
          technical_docs: {
            datasheet?: string;
            manual?: string;
            certifications?: string;
          };
          images: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          short_desc: string;
          brand: string;
          model: string;
          category: string;
          price: string;
          capacity?: string;
          efficiency?: string;
          warranty: string;
          moq: string;
          rating?: number;
          reviews?: number;
          in_stock?: boolean;
          lead_time: string;
          features: string[];
          applications: string[];
          certifications: string[];
          specifications: Record<string, string>;
          technical_docs?: {
            datasheet?: string;
            manual?: string;
            certifications?: string;
          };
          images: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          short_desc?: string;
          brand?: string;
          model?: string;
          category?: string;
          price?: string;
          capacity?: string;
          efficiency?: string;
          warranty?: string;
          moq?: string;
          rating?: number;
          reviews?: number;
          in_stock?: boolean;
          lead_time?: string;
          features?: string[];
          applications?: string[];
          certifications?: string[];
          specifications?: Record<string, string>;
          technical_docs?: {
            datasheet?: string;
            manual?: string;
            certifications?: string;
          };
          images?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          title: string;
          description: string;
          short_desc: string;
          category: string;
          features: string[];
          benefits: string[];
          process: string[];
          applications: string[];
          image: string;
          gallery: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          short_desc: string;
          category: string;
          features: string[];
          benefits: string[];
          process: string[];
          applications: string[];
          image: string;
          gallery: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          short_desc?: string;
          category?: string;
          features?: string[];
          benefits?: string[];
          process?: string[];
          applications?: string[];
          image?: string;
          gallery?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string;
          excerpt: string;
          featured_image: string;
          author: string;
          category: string;
          tags: string[];
          published: boolean;
          views: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          content: string;
          excerpt: string;
          featured_image: string;
          author: string;
          category: string;
          tags: string[];
          published?: boolean;
          views?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          content?: string;
          excerpt?: string;
          featured_image?: string;
          author?: string;
          category?: string;
          tags?: string[];
          published?: boolean;
          views?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          title: string;
          description: string;
          location: string;
          client: string;
          category: string;
          capacity: string;
          year: string;
          status: string;
          featured_image: string;
          gallery: string[];
          technologies: string[];
          challenges: string[];
          solutions: string[];
          results: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          location: string;
          client: string;
          category: string;
          capacity: string;
          year: string;
          status: string;
          featured_image: string;
          gallery: string[];
          technologies: string[];
          challenges: string[];
          solutions: string[];
          results: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          location?: string;
          client?: string;
          category?: string;
          capacity?: string;
          year?: string;
          status?: string;
          featured_image?: string;
          gallery?: string[];
          technologies?: string[];
          challenges?: string[];
          solutions?: string[];
          results?: string[];
          created_at?: string;
          updated_at?: string;
          
        };
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          form_type: string;
          user_type?: string;
          subject: string;
          message: string;
          location?: string;
          product_id?: string;
          service_id?: string;
          system_type?: string;
          monthly_bill?: string;
          property_size?: string;
          business_type?: string;
          power_consumption?: string;
          industrial_scale?: string;
          priority: string;
          source?: string;
          status: 'pending' | 'in_progress' | 'resolved' | 'spam';
          assigned_to?: string;
          follow_up_date?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          user_agent?: string;
          referer?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          email_sent: boolean;
          email_sent_at?: string;
          email_error?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          form_type?: string;
          user_type?: string;
          subject: string;
          message: string;
          location?: string;
          product_id?: string;
          service_id?: string;
          system_type?: string;
          monthly_bill?: string;
          property_size?: string;
          business_type?: string;
          power_consumption?: string;
          industrial_scale?: string;
          priority?: string;
          source?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          assigned_to?: string;
          follow_up_date?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          user_agent?: string;
          referer?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          email_error?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          company?: string;
          form_type?: string;
          user_type?: string;
          subject?: string;
          message?: string;
          location?: string;
          product_id?: string;
          service_id?: string;
          system_type?: string;
          monthly_bill?: string;
          property_size?: string;
          business_type?: string;
          power_consumption?: string;
          industrial_scale?: string;
          priority?: string;
          source?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          assigned_to?: string;
          follow_up_date?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          user_agent?: string;
          referer?: string;
          utm_source?: string;
          utm_medium?: string;
          utm_campaign?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          email_error?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      product_inquiries: {
        Row: {
          id: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          product_id?: string;
          product_name?: string;
          product_category?: string;
          quantity_required?: number;
          budget_range?: string;
          timeline?: string;
          application_type?: string;
          message: string;
          specifications?: string;
          location?: string;
          status: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority: string;
          source?: string;
          email_sent: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          product_id?: string;
          product_name?: string;
          product_category?: string;
          quantity_required?: number;
          budget_range?: string;
          timeline?: string;
          application_type?: string;
          message: string;
          specifications?: string;
          location?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority?: string;
          source?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          company?: string;
          product_id?: string;
          product_name?: string;
          product_category?: string;
          quantity_required?: number;
          budget_range?: string;
          timeline?: string;
          application_type?: string;
          message?: string;
          specifications?: string;
          location?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority?: string;
          source?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_inquiries: {
        Row: {
          id: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          service_id?: string;
          service_name?: string;
          service_category?: string;
          service_type?: string;
          project_timeline?: string;
          budget_range?: string;
          property_type?: string;
          property_size?: string;
          roof_type?: string;
          current_monthly_bill?: string;
          preferred_system_size?: string;
          message: string;
          special_requirements?: string;
          location?: string;
          status: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority: string;
          source?: string;
          email_sent: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string;
          phone: string;
          company?: string;
          service_id?: string;
          service_name?: string;
          service_category?: string;
          service_type?: string;
          project_timeline?: string;
          budget_range?: string;
          property_type?: string;
          property_size?: string;
          roof_type?: string;
          current_monthly_bill?: string;
          preferred_system_size?: string;
          message: string;
          special_requirements?: string;
          location?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority?: string;
          source?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          company?: string;
          service_id?: string;
          service_name?: string;
          service_category?: string;
          service_type?: string;
          project_timeline?: string;
          budget_range?: string;
          property_type?: string;
          property_size?: string;
          roof_type?: string;
          current_monthly_bill?: string;
          preferred_system_size?: string;
          message?: string;
          special_requirements?: string;
          location?: string;
          status?: 'pending' | 'in_progress' | 'resolved' | 'spam';
          priority?: string;
          source?: string;
          email_sent?: boolean;
          email_sent_at?: string;
          metadata?: Record<string, unknown>;
          ip_address?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
